ports:
    - port: 3025
      onOpen: open-browser
tasks:
    - init: >
        npm install &&
        cp .env.example .env
      command: >
        python docs/assets/greeting.py

vscode:
  extensions:
    - esbenp.prettier-vscode